# Generated by Django 3.2.9 on 2022-11-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('decricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=2)),
                ('disponibilidade', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
            ],
        ),
    ]
