# Generated by Django 3.2.9 on 2022-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoria', '0002_rename_decricao_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
