# Generated by Django 3.2.9 on 2022-11-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoria', '0003_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
