# Generated by Django 3.2.9 on 2022-11-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoria', '0005_auto_20221110_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='tempo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
