# Generated by Django 3.2.9 on 2022-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoria', '0006_alter_encomenda_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='bilhete',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
